PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "cadastros_estado" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "nome" varchar(50) NOT NULL, "uf" varchar(2) NOT NULL);
INSERT INTO cadastros_estado VALUES(1,'Acre','AC');
INSERT INTO cadastros_estado VALUES(2,'Alagoas','AL');
INSERT INTO cadastros_estado VALUES(3,'Amazonas','AM');
INSERT INTO cadastros_estado VALUES(4,'Amapá','AP');
INSERT INTO cadastros_estado VALUES(5,'Bahia','BA');
INSERT INTO cadastros_estado VALUES(6,'Ceará','CE');
INSERT INTO cadastros_estado VALUES(7,'Distrito Federal','DF');
INSERT INTO cadastros_estado VALUES(8,'Espírito Santo','ES');
INSERT INTO cadastros_estado VALUES(9,'Goiás','GO');
INSERT INTO cadastros_estado VALUES(10,'Maranhão','MA');
INSERT INTO cadastros_estado VALUES(11,'Minas Gerais','MG');
INSERT INTO cadastros_estado VALUES(12,'Mato Grosso do Sul','MS');
INSERT INTO cadastros_estado VALUES(13,'Mato Grosso','MT');
INSERT INTO cadastros_estado VALUES(14,'Pará','PA');
INSERT INTO cadastros_estado VALUES(15,'Paraíba','PB');
INSERT INTO cadastros_estado VALUES(16,'Pernambuco','PE');
INSERT INTO cadastros_estado VALUES(17,'Piauí','PI');
INSERT INTO cadastros_estado VALUES(18,'Paraná','PR');
INSERT INTO cadastros_estado VALUES(19,'Rio de Janeiro','RJ');
INSERT INTO cadastros_estado VALUES(20,'Rio Grande do Norte','RN');
INSERT INTO cadastros_estado VALUES(21,'Rondônia','RO');
INSERT INTO cadastros_estado VALUES(22,'Roraima','RR');
INSERT INTO cadastros_estado VALUES(23,'Rio Grande do Sul','RS');
INSERT INTO cadastros_estado VALUES(24,'Santa Catarina','SC');
INSERT INTO cadastros_estado VALUES(25,'Sergipe','SE');
INSERT INTO cadastros_estado VALUES(26,'São Paulo','SP');
INSERT INTO cadastros_estado VALUES(27,'Tocantins','TO');
COMMIT;
